version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - n 16.6.0
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run compile && npm start
